# -*- coding: utf-8 -*-
"""Assignment_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvDEmHH0fWUWGKmeBGIxSPIvLmUQvu_2

Assignment 1 :-
Visualize top 5 tokens from a text and you can pick your own paragraph and visualize
"""

import matplotlib.pyplot as plt
from collections import Counter

text = """An AI summarizer is a digital tool that employs advanced algorithms and artificial intelligence to condense long pieces of text into a concise,
easy-to-understand summary, retaining the core ideas and key information of the original content.
These tools are used by students, writers, and professionals to quickly grasp the main points of articles, essays, and other forms of content,
thereby saving time and enhancing productivity by simplifying complex or lengthy information without sacrificing accuracy. """
words = text.split()  # Step 1: Tokenize the text (extract words only)
word_couns = Counter(words)  # Step 2: Count the words
top_5_tokens = word_couns.most_common(5)  # Step 3: Get the top 5 tokens

i = 0
j = 0
top_5_tokens_words = []
top_5_tokens_count = []

for token, count in top_5_tokens:
    top_5_tokens_words.append(token)
    top_5_tokens_count.append(count)
    i += 1
    j += 1

#plt.bar(top_5_tokens.items(), word_couns.count(), color = "green")
plt.bar(top_5_tokens_words, top_5_tokens_count, color = "green")
#plt.bar(word_couns.keys(), word_couns.values(), color = "green")
plt.xlabel("Token")
plt.ylabel("Frequency")
plt.title("Token Frequency")
plt.xticks(rotation = 45)
plt.show()

"""Assignment :- 2
 Create a pie chart of agent tasks and you can modify percentage by changing values
"""

import matplotlib.pyplot as plt
from collections import Counter

task = ["search", "summarize", "translate", "send email", "Generate Report"]
time_taken = [5, 7, 3, 7, 2] # Modify these values as needed
plt.pie(time_taken, labels = task, autopct = '%1.1f%%', colors=plt.cm.Paired.colors)
plt.title("Agentic AI Task Performance")
plt.show()